spring.application.name=expense-tracker

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=${SERVER_PORT:8080}

app.auth.access-token-expiration=${ACCESS_TOKEN_EXPIRATION:15m}
app.auth.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION:30d}