INSERT INTO categories
(id, code, name, type, icon, color_hex, sort_order, active)
VALUES
    (
        gen_random_uuid(),
        'GROCERIES',
        'Groceries',
        'EXPENSE',
        'local_grocery_store',
        '#22B889',
        10,
        TRUE
    ),
    (
        gen_random_uuid(),
        'SHOPPING',
        'Shopping',
        'EXPENSE',
        'shopping_bag',
        '#6C7FF2',
        20,
        TRUE
    ),
    (
        gen_random_uuid(),
        'DINING',
        'Dining',
        'EXPENSE',
        'restaurant',
        '#F59E42',
        30,
        TRUE
    ),
    (
        gen_random_uuid(),
        'TRANSPORT',
        'Transport',
        'EXPENSE',
        'directions_car',
        '#3B82F6',
        40,
        TRUE
    ),
    (
        gen_random_uuid(),
        'BILLS',
        'Bills',
        'EXPENSE',
        'receipt_long',
        '#EAB308',
        50,
        TRUE
    ),
    (
        gen_random_uuid(),
        'HEALTH',
        'Health',
        'EXPENSE',
        'medical_services',
        '#EF4444',
        60,
        TRUE
    ),
    (
        gen_random_uuid(),
        'ENTERTAINMENT',
        'Entertainment',
        'EXPENSE',
        'movie',
        '#A855F7',
        70,
        TRUE
    ),
    (
        gen_random_uuid(),
        'EDUCATION',
        'Education',
        'EXPENSE',
        'school',
        '#0EA5E9',
        80,
        TRUE
    ),
    (
        gen_random_uuid(),
        'TRAVEL',
        'Travel',
        'EXPENSE',
        'flight',
        '#14B8A6',
        90,
        TRUE
    ),
    (
        gen_random_uuid(),
        'OTHER',
        'Other',
        'EXPENSE',
        'category',
        '#64748B',
        100,
        TRUE
    );

INSERT INTO categories
(id, code, name, type, icon, color_hex, sort_order, active)
VALUES
    (
        gen_random_uuid(),
        'FOOD',
        'Food',
        'ITEM',
        'restaurant',
        '#F59E42',
        10,
        TRUE
    ),
    (
        gen_random_uuid(),
        'DRINKS',
        'Drinks',
        'ITEM',
        'local_cafe',
        '#0EA5E9',
        20,
        TRUE
    ),
    (
        gen_random_uuid(),
        'HOUSEHOLD',
        'Household',
        'ITEM',
        'home',
        '#22B889',
        30,
        TRUE
    ),
    (
        gen_random_uuid(),
        'PERSONAL_CARE',
        'Personal care',
        'ITEM',
        'spa',
        '#EC4899',
        40,
        TRUE
    ),
    (
        gen_random_uuid(),
        'CLOTHING',
        'Clothing',
        'ITEM',
        'checkroom',
        '#8B5CF6',
        50,
        TRUE
    ),
    (
        gen_random_uuid(),
        'ELECTRONICS',
        'Electronics',
        'ITEM',
        'devices',
        '#3B82F6',
        60,
        TRUE
    ),
    (
        gen_random_uuid(),
        'HEALTH',
        'Health',
        'ITEM',
        'medical_services',
        '#EF4444',
        70,
        TRUE
    ),
    (
        gen_random_uuid(),
        'OTHER',
        'Other',
        'ITEM',
        'category',
        '#64748B',
        100,
        TRUE
    );